spring.application.name=aplicacao-spring
# Ativa o console do H2 no navegador
spring.h2.console.enabled=true
# Caminho para acessar o console
spring.h2.console.path=/h2-console

spring.h2.console.settings.web-allow-others=true
server.servlet.context-path=/

spring.security.frame-options.disable=true

# Configuração da URL do banco (em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostra no console do VS Code os comandos SQL que o Spring está fazendo
spring.jpa.show-sql=true